version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    working_dir: /app
  db:
    image: postgres:14.2
    container_name: "online-store-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
      POSTGRES_PASSWORD: gormdeptrai3
